export const skills = {
  frontend: [
    "React",
    "React Native",
    "TypeScript",
    "JavaScript",
    "HTML5",
    "CSS3",
    "Tailwind CSS",
    "Zustand",
    "ZOD",
    "TanstackQuery(ReactQuery)",
    "Storybook",
    "React-Router-Dom v6",
  ],
  tools: [
    "Git",
    "GitHub",
    "Figma",
    "Slack",
    "VS Code",
    "Cursor",
    "Webpack",
    "Vite",
    "npm",
    "pnpm",
    "yarn",
    "Postman",
  ],
  additional: [
    "Responsive Design",
    "RESTful API",
    "Performance Optimization",
    "SEO",
    "SSE",
    "Vercel",
    "CI/CD",
  ],
};
