export const landingSkillGroups = [
  {
    label: "Core",
    skills: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "TypeScript",
      "React · React Native",
      "Next.js",
    ],
  },
  {
    label: "State & Data",
    skills: [
      "Zustand",
      "Redux",
      "TanstackQuery",
      "Zod",
      "React Router",
      "RESTful API",
      "GraphQL",
      "SSE",
    ],
  },
  {
    label: "UI & Quality",
    skills: [
      "Tailwind CSS",
      "Storybook",
      "Framer Motion",
      "Responsive Design",
      "Performance Optimization",
      "SEO",
    ],
  },
  {
    label: "Build & Test",
    skills: [
      "Vite",
      "Webpack",
      "npm",
      "pnpm",
      "ESLint",
      "Prettier",
      "Jest",
      "Vitest",
      "Cypress",
      "Playwright",
    ],
  },
  {
    label: "Tools & Collab",
    skills: [
      "Git",
      "GitHub",
      "GitLab",
      "Figma",
      "Postman",
      "Vercel",
      "CI/CD",
      "VS Code",
      "Cursor",
      "Slack",
      "Notion",
      "Jira",
    ],
  },
] as const;
